# Generated by Django 5.0.6 on 2024-07-27 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dresses', '0009_alter_dresses_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_price', models.FloatField()),
                ('is_payment_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_dress_booking_days',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days', models.DateField()),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dresses.dresses')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_booking_days_set', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('comapny_name', models.CharField(blank=True, max_length=30, null=True)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('application_notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('Target_dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dress_item_set', to='Dresses.dresses')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_set', to='orders.order')),
            ],
        ),
    ]
