# Generated by Django 5.0.6 on 2024-07-27 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_applied_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_dress_booking_days',
            name='order',
        ),
        migrations.AddField(
            model_name='order_dress_booking_days',
            name='OrderItem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderItem_booking_days_set', to='orders.orderitem'),
            preserve_default=False,
        ),
    ]
