version: '3.8'

services:
  django:
    build:
      context: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./code/db.sqlite3:/code/db.sqlite3  # Ensure SQLite database file persists
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build:
      context: .
    container_name: celery
    command: celery -A config worker -l info
    volumes:
      - .:/code
      - ./code/db.sqlite3:/code/db.sqlite3  # Ensure SQLite database file persists
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
    container_name: celery_beat
    command: celery -A config beat -l info
    volumes:
      - .:/code
      - ./code/db.sqlite3:/code/db.sqlite3  # Ensure SQLite database file persists
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:6
    container_name: redis
