# Generated by Django 5.0.6 on 2024-07-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteOwner_receivable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteowner_receivable',
            name='is_active',
        ),
    ]
