# Generated by Django 5.0.6 on 2024-08-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SiteOwner_receivable", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteowner_receivable",
            options={
                "verbose_name": "Site Owner Receivable",
                "verbose_name_plural": "Site Owner Receivable",
            },
        ),
    ]
