# Generated by Django 5.0.6 on 2024-08-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenter_details',
            name='payout_account_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
