# Generated by Django 5.0.6 on 2024-07-02 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dresses', '0006_favorite_dresses'),
        ('investment', '0003_remove_investmenter_details_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='investmenter_dresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dresses.dresses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investmenter_dresses_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
