# Generated by Django 5.0.6 on 2024-08-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_remove_investmenter_details_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenter_details',
            name='iban',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
