# Generated by Django 5.0.6 on 2024-08-18 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0006_investmenter_details_bank_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investmenter_details",
            name="iban",
        ),
        migrations.RemoveField(
            model_name="investmenter_details",
            name="payout_account_id",
        ),
        migrations.AddField(
            model_name="investmenter_balance",
            name="investmenter_detailsFk",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investmenter_bank",
                to="investment.investmenter_details",
            ),
            preserve_default=False,
        ),
    ]
