# Generated by Django 5.0.6 on 2024-08-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_investmenter_details_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenter_details',
            name='bank_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmenter_details',
            name='credit_card_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
