# Generated by Django 5.0.6 on 2024-08-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_investmenter_details_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenter_balance',
            name='curr_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investmenter_balance',
            name='total_balance',
            field=models.IntegerField(default=0),
        ),
    ]
