# Generated by Django 5.0.6 on 2024-09-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0008_alter_investmenter_details_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmenter_details',
            options={'verbose_name': 'Investmenter Bank Details', 'verbose_name_plural': 'Investmenter Bank Details'},
        ),
    ]
