# Generated by Django 5.0.6 on 2024-07-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dresses", "0006_favorite_dresses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dresses",
            name="actual_price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="dresses",
            name="price_for_3days",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="dresses",
            name="price_for_6days",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="dresses",
            name="price_for_8days",
            field=models.IntegerField(),
        ),
    ]
