# Generated by Django 5.0.6 on 2024-07-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dresses', '0008_dresses_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dresses',
            name='product_type',
            field=models.CharField(choices=[('Dress', 'Dress'), ('Bag', 'Bag')], max_length=10),
        ),
    ]
