# Generated by Django 5.0.6 on 2024-07-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dresses', '0009_alter_dresses_product_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dress_busy_days',
            unique_together={('dress', 'busy_day')},
        ),
    ]
