# Generated by Django 5.0.6 on 2024-08-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dresses", "0011_dress_busy_days_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dresses",
            name="Num_of_rentals",
            field=models.IntegerField(default=0),
        ),
    ]
