# Generated by Django 5.0.6 on 2024-07-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_invitation_points',
            name='user_code',
            field=models.CharField(default=1, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
