# Generated by Django 5.0.6 on 2024-08-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invitation", "0002_user_invitation_points_user_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invitation_points_trade",
            options={
                "verbose_name": "Trade points with coupons",
                "verbose_name_plural": "Trade points with coupons",
            },
        ),
    ]
