# Generated by Django 5.0.6 on 2024-07-02 17:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating_stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating stars')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerReviews_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Reviews',
                'verbose_name_plural': 'Customer Reviews',
                'ordering': ['-uploaded_at'],
                'unique_together': {('user', 'feedback')},
                'index_together': {('user', 'feedback')},
            },
        ),
    ]
