# Generated by Django 5.0.6 on 2024-07-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
