# Generated by Django 5.0.6 on 2024-07-31 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0002_coupon_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_used',
        ),
    ]
