# Generated by Django 5.0.6 on 2024-09-12 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_alter_user_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_Date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
