# Generated by Django 5.0.6 on 2024-09-01 18:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "FAQ_and_terms",
            "0002_alter_faq_options_alter_terms_and_condations_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="terms_and_condations",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
