# Generated by Django 5.0.6 on 2024-09-02 11:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FAQ_and_terms", "0003_alter_terms_and_condations_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=tinymce.models.HTMLField(),
        ),
    ]
